set_property SRC_FILE_INFO {cfile:{C:/Users/Dat Pham/Downloads/Source/timing_constraints.sdc} rfile:../../../../timing_constraints.sdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Dat Pham/Downloads/Source/timing_constraints.xdc} rfile:../../../../timing_constraints.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk -period 2.857 [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty 0.1 [get_clocks clk]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {reset start_in}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {reset start_in}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {A_i[*]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {A_i[*]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {B_i[*]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {B_i[*]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {C_i[*]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {C_i[*]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {D_i[*]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {D_i[*]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {E_i[*]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {E_i[*]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {F_i[*]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {F_i[*]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {G_i[*]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {G_i[*]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {H_i[*]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {H_i[*]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w0_sha256[*]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w0_sha256[*]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w1_sha256[*]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w1_sha256[*]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w2_sha256[*]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w2_sha256[*]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w3_sha256[*]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w3_sha256[*]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w4_sha256[*]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w4_sha256[*]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w5_sha256[*]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w5_sha256[*]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w6_sha256[*]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w6_sha256[*]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w7_sha256[*]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w7_sha256[*]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w8_sha256[*]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w8_sha256[*]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w9_sha256[*]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w9_sha256[*]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w10_sha256[*]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w10_sha256[*]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w11_sha256[*]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w11_sha256[*]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w12_sha256[*]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w12_sha256[*]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w13_sha256[*]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w13_sha256[*]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w14_sha256[*]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w14_sha256[*]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w15_sha256[*]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w15_sha256[*]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAD_addr_in[*]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAD_addr_in[*]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAD_data_in[*]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAD_data_in[*]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAD_wea_in[*]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAD_wea_in[*]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAI_addr_in[*]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAI_addr_in[*]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAI_data_in[*]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAI_data_in[*]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAI_wea_in[*]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAI_wea_in[*]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 1.4 [get_ports {sha256_result[*]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.2 [get_ports {sha256_result[*]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 1.4 [get_ports {sha256_valid}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.2 [get_ports {sha256_valid}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports reset]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 20 [current_design]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_max_transition 0.5 [current_design]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_max_capacitance 0.5 [current_design]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -through [get_pins -hierarchical *reg*/Q]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
group_path -name "SHA_DATAPATH" -from [get_ports {A_i[*] B_i[*] C_i[*] D_i[*] E_i[*] F_i[*] G_i[*] H_i[*]}] -to [get_ports {sha256_result[*] sha256_valid}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
group_path -name "W_INPUTS" -from [get_ports {w*_sha256[*]}] -to [get_ports {sha256_result[*] sha256_valid}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_ports reset]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.857 -name clk -waveform {0.000 1.4285} [get_ports clk]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty 0.1 [get_clocks clk]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {reset start_in}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {reset start_in}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {A_i[*] B_i[*] C_i[*] D_i[*] E_i[*] F_i[*] G_i[*] H_i[*]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {A_i[*] B_i[*] C_i[*] D_i[*] E_i[*] F_i[*] G_i[*] H_i[*]}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {w*_sha256[*]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {w*_sha256[*]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAD_addr_in[*] DMAD_data_in[*] DMAD_wea_in[*]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAD_addr_in[*] DMAD_data_in[*] DMAD_wea_in[*]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.4 [get_ports {DMAI_addr_in[*] DMAI_data_in[*] DMAI_wea_in[*]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.2 [get_ports {DMAI_addr_in[*] DMAI_data_in[*] DMAI_wea_in[*]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 1.4 [get_ports {sha256_result[*]}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.2 [get_ports {sha256_result[*]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 1.4 [get_ports {sha256_valid}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.2 [get_ports {sha256_valid}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports reset]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_fanout 20 [current_design]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_max_transition 0.5 [current_design]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -setup 2 -to [get_pins {*reg*/D}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 1 -to [get_pins {*reg*/D}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_ports reset]
