# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Dat Pham/Downloads/Source/project_1/project_1.runs/synth_1/RISC_Sha_tb.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvc900-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Dat Pham/Downloads/Source/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Dat Pham/Downloads/Source/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Dat Pham/Downloads/Source/project_1/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {C:/Users/Dat Pham/Downloads/Source/Adder1.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder1_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder2.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder2_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder3.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder3_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder4.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder4_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Adder_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/CH_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Ch.v}
  {C:/Users/Dat Pham/Downloads/Source/Delta0.v}
  {C:/Users/Dat Pham/Downloads/Source/Delta0_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Delta1.v}
  {C:/Users/Dat Pham/Downloads/Source/Delta1_64.v}
  {C:/Users/Dat Pham/Downloads/Source/FSM_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/Maj.v}
  {C:/Users/Dat Pham/Downloads/Source/Maj_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Mux32.v}
  {C:/Users/Dat Pham/Downloads/Source/Mux32_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Mux_res_sha.v}
  {C:/Users/Dat Pham/Downloads/Source/Parise_mux.v}
  {C:/Users/Dat Pham/Downloads/Source/Parise_mux64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg0.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg0_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg10.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg10_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg11.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg11_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg12.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg12_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg13.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg13_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg14.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg14_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg15.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg15_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg1_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg1_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg2_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg2_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg32.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg32_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg3_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg3_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg4_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg4_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg5.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg5_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg6.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg6_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg7.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg7_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg8.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg8_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg9.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg9_64.v}
  {C:/Users/Dat Pham/Downloads/Source/RegI.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_A.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_A_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_B.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_B_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_C.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_C_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_D.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_D_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_E.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_E_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_F.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_F_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_G.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_G_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_H.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_H_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_J.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_K.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_K_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Reg_res256.v}
  {C:/Users/Dat Pham/Downloads/Source/Sigma0.v}
  {C:/Users/Dat Pham/Downloads/Source/Sigma0_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Sigma1.v}
  {C:/Users/Dat Pham/Downloads/Source/Sigma1_64.v}
  {C:/Users/Dat Pham/Downloads/Source/Top_Sha.v}
  {C:/Users/Dat Pham/Downloads/Source/tb_FSM.v}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Dat Pham/Downloads/Source/timing_constraints.sdc}}
set_property used_in_implementation false [get_files {{C:/Users/Dat Pham/Downloads/Source/timing_constraints.sdc}}]

read_xdc {{C:/Users/Dat Pham/Downloads/Source/timing_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Dat Pham/Downloads/Source/timing_constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RISC_Sha_tb -part xczu9eg-ffvc900-3-e -directive PerformanceOptimized -keep_equivalent_registers -no_lc -shreg_min_size 5 -retiming -no_iobuf
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISC_Sha_tb.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISC_Sha_tb_utilization_synth.rpt -pb RISC_Sha_tb_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
